"""The one reader of the rulings store (private/oracle, sops-encrypted).

Full entries live in one file per topic (topics/<topic>.md); rulings.md is the
one-line index rendered from them by listing(). Nothing else parses the store.
Reading it needs a sops key in SOPS_AGE_KEY_FILE or SOPS_AGE_KEY; without one it
raises rather than reading as empty.
"""

import enum
import hashlib
import re
import subprocess
from dataclasses import dataclass
from functools import cache
from pathlib import Path

from btcopilot.promptdir import key_present

ROOT = Path(__file__).parents[1]
STORE = ROOT / "private" / "oracle"
INDEX = STORE / "rulings.md"
TOPICS = STORE / "topics"
EVIDENCE = STORE / "evidence.md"
FIELDS = ("id", "statement", "kind", "tags", "status", "evidence_count", "origin")
LISTED = ("id", "status", "statement", "topic", "cited")
ROW = re.compile(r"^R-\d{4} \|")
ID = re.compile(r"R-\d{4}")
QUOTE = "> "
GIST = 90
SENTENCE = re.compile(r"(?<=[.;:?])\s|\s—\s")
PREAMBLE = (
    "# rulings — the index, one line per ruling; generated by bin/oracleindex.py, never hand-edited\n"
    f"Fields: {' | '.join(LISTED)}. The statement is its first sentence, cut at {GIST} characters (…);\n"
    "the full entry is in topics/<topic>.md, the quotes in evidence.md. cited = tests citing it.\n"
)


class Kind(enum.Enum):
    Rule = "rule"
    Journey = "journey"
    Defect = "defect"


class Status(enum.Enum):
    Ok = "OK"
    Gap = "GAP"
    Waived = "WAIVED"
    Superseded = "SUPERSEDED"
    TestOwed = "TEST OWED"
    Duplicate = "DUPLICATE"


POINTING = {Status.Superseded, Status.Duplicate}


class Topic(enum.Enum):
    Picture = "picture"
    Clusters = "clusters"
    Coach = "coach"
    ProductConcept = "product-concept"
    Review = "review"
    Record = "record"
    Shell = "shell"
    Platform = "platform"
    Corpus = "corpus"
    Process = "process"


class Tag(enum.Enum):
    Account = "account"
    Admin = "admin"
    Affordance = "affordance"
    Agents = "agents"
    Anxiety = "anxiety"
    Architecture = "architecture"
    Avatar = "avatar"
    Beta = "beta"
    Business = "business"
    Chalkboard = "chalkboard"
    Chat = "chat"
    Chips = "chips"
    Clusters = "clusters"
    Coach = "coach"
    Comms = "comms"
    Composer = "composer"
    Conflict = "conflict"
    Corpus = "corpus"
    Cost = "cost"
    Cutoff = "cutoff"
    DataModel = "data-model"
    DataNature = "data-nature"
    Database = "database"
    Defect = "defect"
    DefinedSelf = "defined-self"
    Deploy = "deploy"
    Design = "design"
    DesignProcess = "design-process"
    Distance = "distance"
    Dns = "dns"
    Drawability = "drawability"
    Drawing = "drawing"
    Editor = "editor"
    Evaluation = "evaluation"
    Events = "events"
    Extraction = "extraction"
    FamilyDiagram = "family-diagram"
    Fixtures = "fixtures"
    Functioning = "functioning"
    Fusion = "fusion"
    Identity = "identity"
    Import = "import"
    Irr = "irr"
    Layout = "layout"
    ListView = "list-view"
    Logging = "logging"
    Memory = "memory"
    Model = "model"
    Money = "money"
    Navigation = "navigation"
    Observability = "observability"
    Onboarding = "onboarding"
    Picture = "picture"
    Plan = "plan"
    Platform = "platform"
    PlayByPlay = "play-by-play"
    Privacy = "privacy"
    ProApp = "pro-app"
    Process = "process"
    ProductConcept = "product-concept"
    Projection = "projection"
    Prompts = "prompts"
    QuestionLanguage = "question-language"
    Record = "record"
    Recording = "recording"
    Release = "release"
    Repo = "repo"
    Review = "review"
    Roles = "roles"
    Sarf = "sarf"
    Scrolling = "scrolling"
    Security = "security"
    Sessions = "sessions"
    Settings = "settings"
    Shell = "shell"
    Symbols = "symbols"
    Symptom = "symptom"
    Testing = "testing"
    Timing = "timing"
    TitleRow = "title-row"
    Tokens = "tokens"
    Tooling = "tooling"
    Toward = "toward"
    Traceability = "traceability"
    Training = "training"
    Triangle = "triangle"
    UiStandards = "ui-standards"
    VisualLanguage = "visual-language"
    Voice = "voice"
    Wide = "wide"
    Words = "words"


GROUPS = {
    Topic.Picture: (
        Tag.Picture, Tag.Symbols, Tag.Drawing, Tag.Layout, Tag.Drawability, Tag.VisualLanguage,
        Tag.FamilyDiagram, Tag.TitleRow, Tag.Scrolling, Tag.Wide,
    ),
    Topic.Clusters: (Tag.PlayByPlay, Tag.Clusters, Tag.Events, Tag.Timing, Tag.Toward),
    Topic.Coach: (
        Tag.Coach, Tag.Prompts, Tag.Chat, Tag.Sessions, Tag.Composer, Tag.Tokens, Tag.Model,
        Tag.Voice, Tag.Memory, Tag.QuestionLanguage,
    ),
    Topic.ProductConcept: (
        Tag.ProductConcept, Tag.Business, Tag.Money, Tag.Beta, Tag.ProApp, Tag.Onboarding,
        Tag.Account, Tag.Plan, Tag.Identity, Tag.Roles,
    ),
    Topic.Review: (
        Tag.Training, Tag.Review, Tag.Sarf, Tag.Irr, Tag.Evaluation, Tag.Triangle, Tag.Anxiety,
        Tag.Conflict, Tag.Distance, Tag.Fusion, Tag.Projection, Tag.Symptom, Tag.Functioning,
        Tag.DefinedSelf, Tag.Cutoff,
    ),
    Topic.Record: (Tag.Record, Tag.DataModel, Tag.DataNature, Tag.Database, Tag.Import, Tag.Extraction),
    Topic.Shell: (
        Tag.Shell, Tag.ListView, Tag.UiStandards, Tag.Editor, Tag.Chalkboard, Tag.Chips, Tag.Words,
        Tag.Navigation, Tag.Settings, Tag.Design, Tag.Affordance, Tag.Avatar, Tag.Recording,
    ),
    Topic.Platform: (
        Tag.Architecture, Tag.Deploy, Tag.Platform, Tag.Security, Tag.Observability, Tag.Release,
        Tag.Dns, Tag.Logging, Tag.Privacy, Tag.Admin,
    ),
    Topic.Corpus: (Tag.Corpus, Tag.Repo, Tag.Tooling, Tag.Testing, Tag.Traceability, Tag.Fixtures, Tag.Defect),
    Topic.Process: (Tag.Process, Tag.DesignProcess, Tag.Agents, Tag.Comms, Tag.Cost),
}
# A ruling's full entry lives in the topic file of its first tag.
TOPIC = {tag: topic for topic, tags in GROUPS.items() for tag in tags}


@dataclass(frozen=True)
class Ruling:
    id: str
    statement: str
    kind: Kind
    tags: tuple[Tag, ...]
    status: Status
    pointer: tuple[str, ...]
    evidence_count: int
    origin: str
    topic: Topic


def decrypt(path: Path) -> str:
    if not key_present():
        raise RuntimeError(
            f"{path.relative_to(ROOT)} needs a sops key: set SOPS_AGE_KEY_FILE or SOPS_AGE_KEY"
        )
    done = subprocess.run(
        ["sops", "-d", str(path)], capture_output=True, text=True, check=True
    )
    return done.stdout


def status(field: str) -> tuple[Status, tuple[str, ...]]:
    word = next((s for s in Status if field == s.value or field.startswith(s.value + " ")), None)
    if word is None:
        raise ValueError(f"status {field!r} is not in the closed vocabulary")
    pointer = tuple(ID.findall(field[len(word.value) :]))
    if (word in POINTING) != bool(pointer):
        raise ValueError(f"status {field!r} must name a ruling exactly when it is {'/'.join(s.value for s in POINTING)}")
    return word, pointer


def ruling(row: str, topic: Topic) -> Ruling:
    cols = [c.strip() for c in row.split(" | ")]
    if len(cols) != len(FIELDS):
        raise ValueError(f"{cols[0]} has {len(cols)} fields, not 7")
    rid, statement, kind, tags, stat, count, origin = cols
    if not re.fullmatch(r"R-\d{4}", rid) or not statement or not origin or not tags:
        raise ValueError(f"{rid} has an empty or malformed field")
    word, pointer = status(stat)
    found = tuple(Tag(t.strip()) for t in tags.split(","))
    if TOPIC[found[0]] is not topic:
        raise ValueError(f"{rid} belongs in topics/{TOPIC[found[0]].value}.md, the topic of its first tag")
    return Ruling(
        id=rid,
        statement=statement,
        kind=Kind(kind),
        tags=found,
        status=word,
        pointer=pointer,
        evidence_count=int(count),
        origin=origin,
        topic=topic,
    )


def parse(texts: dict[Topic, str]) -> dict[str, Ruling]:
    found = {}
    for topic, text in texts.items():
        for row in text.splitlines():
            if not ROW.match(row):
                continue
            r = ruling(row, topic)
            if r.id in found:
                raise ValueError(f"{r.id} appears twice")
            found[r.id] = r
    for r in found.values():
        for other in r.pointer:
            if other not in found:
                raise ValueError(f"{r.id} points at {other}, which is not in the store")
    return dict(sorted(found.items()))


def topicfile(topic: Topic) -> Path:
    return TOPICS / f"{topic.value}.md"


@cache
def index() -> str:
    return decrypt(INDEX)


@cache
def rulings() -> dict[str, Ruling]:
    return parse({t: decrypt(topicfile(t)) for t in Topic})


def gist(statement: str) -> str:
    m = SENTENCE.search(statement)
    first = statement[: m.start()].rstrip(" .;:") if m else statement
    return first if len(first) <= GIST else first[:GIST].rsplit(" ", 1)[0] + "…"


def listed(r: Ruling, cited: int) -> str:
    stat = " ".join([r.status.value, ",".join(r.pointer)]) if r.pointer else r.status.value
    return " | ".join([r.id, stat, gist(r.statement), r.topic.value, str(cited)])


def listing(cited: dict[str, int]) -> str:
    """The index: a fixed preamble, then one line per ruling in id order."""
    return PREAMBLE + "".join(listed(r, cited.get(r.id, 0)) + "\n" for r in rulings().values())


def quoted(text: str) -> dict[str, list[str]]:
    """Each ruling's quotes. After a free-text header, a block is a line that is
    exactly the id, then its "> " quote lines, then a blank line."""
    out, current = {}, None
    for line in text.splitlines():
        if re.fullmatch(r"R-\d{4}", line):
            if line in out:
                raise ValueError(f"evidence for {line} appears twice")
            current = out[line] = []
        elif not line.strip():
            current = None
        elif current is not None:
            if not line.startswith(QUOTE):
                raise ValueError(f"evidence line under an id does not start with {QUOTE!r}: {line[:40]!r}")
            current.append(" ".join(line[len(QUOTE) :].split()))
    return out


@cache
def quotes() -> dict[str, list[str]]:
    return quoted(decrypt(EVIDENCE))


def fingerprints() -> dict[str, set[str]]:
    return {
        rid: {hashlib.sha256(q.encode()).hexdigest()[:16] for q in qs}
        for rid, qs in quotes().items()
    }


def pinned(text: str) -> dict[str, list[str]]:
    return {rid: digests for rid, *digests in (l.split() for l in text.splitlines() if l.strip())}


def pin(text: str) -> str:
    """The fingerprint file with new ids and new quotes appended; nothing already
    pinned is dropped or reordered. An id with no quotes yet is pinned bare."""
    old, now = pinned(text), fingerprints()
    rows = [[rid, *ds, *sorted(now.get(rid, set()) - set(ds))] for rid, ds in old.items()]
    rows += [[rid, *sorted(now.get(rid, set()))] for rid in sorted((set(rulings()) | set(now)) - set(old))]
    return "".join(" ".join(r) + "\n" for r in rows)
