import enum

from sqlalchemy import Column, Text, Integer, Boolean, Date, JSON, Enum
from sqlalchemy.orm import relationship

from btcopilot.extensions import db
from btcopilot.llmutil import response_text_sync
from btcopilot.modelmixin import ModelMixin


class DiscussionStatus(enum.StrEnum):
    Pending = "pending"
    Generating = "generating"
    Failed = "failed"
    PendingExtraction = "pending_extraction"
    Extracting = "extracting"
    Ready = "ready"


class Discussion(db.Model, ModelMixin):

    __tablename__ = "discussions"

    user_id = Column(Integer, db.ForeignKey("users.id"))
    diagram_id = Column(Integer, db.ForeignKey("diagrams.id"))
    summary = Column(Text)
    discussion_date = Column(
        Date,
        nullable=True,
        comment="Date of the actual discussion/session (for accurate relative date extraction)",
    )
    last_topic = Column(
        Text,
        comment="A the topic that the model should follow the user on, e.g. presenting problem, new issue",
    )
    status = Column(
        Enum(DiscussionStatus, values_callable=lambda e: [x.value for x in e]),
        default=DiscussionStatus.Pending,
        nullable=False,
        server_default=DiscussionStatus.Pending.value,
    )
    extracting = Column(
        Boolean,
        default=False,
        nullable=False,
        comment="Whether background extraction job should run for this discussion's statements",
    )
    synthetic = Column(
        Boolean,
        default=False,
        nullable=False,
        comment="Whether this discussion was generated by synthetic conversation testing",
    )
    synthetic_persona = Column(
        JSON,
        nullable=True,
        comment="Persona data for synthetic conversations (name, background, traits, presenting_problem)",
    )
    synthetic_persona_id = Column(
        Integer,
        db.ForeignKey("synthetic_personas.id"),
        nullable=True,
        comment="FK to synthetic_personas for generated persona linkage",
    )
    calibration_report = Column(JSON, nullable=True)
    calibration_advice = Column(JSON, nullable=True)
    statement_reviews = Column(JSON, nullable=True)
    extracted_through_order = Column(
        Integer,
        nullable=True,
        comment="Re-extraction cursor: highest Statement.order whose extraction "
        "has been accepted/committed. NULL = nothing accepted yet (extract from "
        "the start, legacy behaviour). Advances only on full PDP accept.",
    )
    pending_extracted_through_order = Column(
        Integer,
        nullable=True,
        comment="Max Statement.order included in the most recent extract, held "
        "until that PDP is accepted; on full accept it is promoted to "
        "extracted_through_order. NULL when no extract awaits acceptance.",
    )
    user = relationship("User")
    diagram = relationship("Diagram", back_populates="discussions")
    statements = relationship(
        "Statement",
        back_populates="discussion",
        order_by="Statement.order",
        cascade="all, delete-orphan",
    )
    speakers = relationship(
        "Speaker",
        foreign_keys="Speaker.discussion_id",
        back_populates="discussion",
        cascade="all, delete-orphan",
    )

    chat_user_speaker_id = Column(
        Integer,
        db.ForeignKey("speakers.id"),
        nullable=True,
        comment="The user speaker in a chat context",
    )
    chat_user_speaker = relationship(
        "Speaker",
        foreign_keys=[chat_user_speaker_id],
        back_populates="user_discussion",
        uselist=False,
    )

    chat_ai_speaker_id = Column(
        Integer,
        db.ForeignKey("speakers.id"),
        nullable=True,
        comment="The AI speaker in a chat context",
    )
    chat_ai_speaker = relationship(
        "Speaker",
        foreign_keys=[chat_ai_speaker_id],
        back_populates="ai_discussion",
        uselist=False,
    )

    def conversation_history(self, up_to_order: int | None = None) -> str:
        statements = self.statements
        if up_to_order is not None:
            statements = [s for s in statements if (s.order or 0) < up_to_order]

        return (
            "\n".join(
                [
                    f"{s.speaker.name if s.speaker else 'Unknown'}: {s.text}"
                    for s in statements
                ]
            )
            if statements
            else "(No statements in this discussion yet)"
        )

    def update_summary(self):
        from btcopilot.personal.prompts import SUMMARIZE_MESSAGES_PROMPT

        self.summary = response_text_sync(
            SUMMARIZE_MESSAGES_PROMPT.format(
                conversation_history=self.conversation_history()
            ),
        )

    def next_order(self) -> int:
        from btcopilot.personal.models import Statement

        # Serialize order allocation per discussion. A bare max+1 lets two
        # concurrent chat turns read the same max and assign duplicate
        # Statement.order, which corrupts the re-extraction window boundary
        # (statements on the cursor edge get misclassified, silently dropping
        # or duplicating conversation in the next extract). The SELECT FOR
        # UPDATE on the parent row blocks a second writer until this turn
        # commits, so each turn sees the prior turn's committed orders.
        # SQLite (tests) ignores FOR UPDATE; PostgreSQL (prod) enforces it.
        db.session.query(Discussion).filter(
            Discussion.id == self.id
        ).with_for_update().one()
        max_order = (
            db.session.query(db.func.max(Statement.order))
            .filter(Statement.discussion_id == self.id)
            .scalar()
        )
        return (max_order or 0) + 1
