from btcopilot.personal.models import Discussion


ASSEMBLY_AI_TRANSCRIPT_JSON = {
    "id": "87fa1e92-62d0-441e-9ca4-87ac8cdb365d",
    "language_model": "assemblyai_default",
    "acoustic_model": "assemblyai_default",
    "language_code": "en_us",
    "status": "completed",
    "audio_url": "https://cdn.assemblyai.com/upload/50e9dedb-0460-402a-81b0-b3b1e34fab66",
    "text": "I'm Dr. Murray Boyne. This group today includes Greg Sashkin, who's the therapist, and Mr. John Vinceguero and Mrs. Anita Vinceguero. And if I hear. Let me ask the Vinceros, how did Greg wangle you into this? I don't really think he really wangled us early into it. Well, what happened? Well, we were going to this other program before this over at the stress center, and I guess things got a little bit hectical or something, likely by them wanting us to come there, you know, at certain times and stuff. And they sort of said things about us that really wasn't even true. They were saying things that we wasn't coming in on time, we wasn't doing these things right when we were there, wasn't taking care of the baby. Right this way. How long did you go there before you came here? What would you say? About a month? About a month. And then. So you were referred here or you found this place? We were referred here by what court?",
    "words": [
        {
            "text": "I'm",
            "start": 17520,
            "end": 17720,
            "confidence": 0.9609375,
            "speaker": "B",
        },
        {
            "text": "Dr.",
            "start": 17720,
            "end": 17960,
            "confidence": 0.98828,
            "speaker": "B",
        },
        {
            "text": "Murray",
            "start": 17960,
            "end": 18360,
            "confidence": 0.8414714,
            "speaker": "B",
        },
        {
            "text": "Boyne.",
            "start": 18360,
            "end": 18960,
            "confidence": 0.6133626,
            "speaker": "B",
        },
        {
            "text": "This",
            "start": 20000,
            "end": 20320,
            "confidence": 0.9785156,
            "speaker": "B",
        },
        {
            "text": "group",
            "start": 20320,
            "end": 20600,
            "confidence": 0.99902344,
            "speaker": "B",
        },
        {
            "text": "today",
            "start": 20600,
            "end": 20960,
            "confidence": 0.9921875,
            "speaker": "B",
        },
        {
            "text": "includes",
            "start": 20960,
            "end": 21760,
            "confidence": 0.9914551,
            "speaker": "B",
        },
        {
            "text": "Greg",
            "start": 23200,
            "end": 23600,
            "confidence": 0.98828125,
            "speaker": "B",
        },
        {
            "text": "Sashkin,",
            "start": 23600,
            "end": 24480,
            "confidence": 0.9473877,
            "speaker": "B",
        },
        {
            "text": "who's",
            "start": 24800,
            "end": 25240,
            "confidence": 0.90722656,
            "speaker": "B",
        },
        {
            "text": "the",
            "start": 25240,
            "end": 25400,
            "confidence": 0.9951172,
            "speaker": "B",
        },
        {
            "text": "therapist,",
            "start": 25400,
            "end": 26000,
            "confidence": 0.99609375,
            "speaker": "B",
        },
        {
            "text": "and",
            "start": 27330,
            "end": 27570,
            "confidence": 0.9550781,
            "speaker": "B",
        },
        {
            "text": "Mr.",
            "start": 29250,
            "end": 29690,
            "confidence": 0.99951,
            "speaker": "B",
        },
        {
            "text": "John",
            "start": 29690,
            "end": 30050,
            "confidence": 0.99365234,
            "speaker": "B",
        },
        {
            "text": "Vinceguero",
            "start": 30050,
            "end": 31010,
            "confidence": 0.8442383,
            "speaker": "B",
        },
        {
            "text": "and",
            "start": 31170,
            "end": 31530,
            "confidence": 0.7055664,
            "speaker": "B",
        },
        {
            "text": "Mrs.",
            "start": 31530,
            "end": 32050,
            "confidence": 0.99487,
            "speaker": "B",
        },
        {
            "text": "Anita",
            "start": 32050,
            "end": 32850,
            "confidence": 0.8515625,
            "speaker": "B",
        },
        {
            "text": "Vinceguero.",
            "start": 32850,
            "end": 33810,
            "confidence": 0.85148114,
            "speaker": "B",
        },
        {
            "text": "And",
            "start": 36690,
            "end": 37010,
            "confidence": 0.59375,
            "speaker": "B",
        },
        {
            "text": "if",
            "start": 37010,
            "end": 37250,
            "confidence": 0.9975586,
            "speaker": "B",
        },
        {
            "text": "I",
            "start": 37250,
            "end": 37450,
            "confidence": 0.9995117,
            "speaker": "B",
        },
        {
            "text": "hear.",
            "start": 37450,
            "end": 37730,
            "confidence": 0.9868164,
            "speaker": "B",
        },
        {
            "text": "Let",
            "start": 37970,
            "end": 38290,
            "confidence": 0.94873047,
            "speaker": "B",
        },
        {
            "text": "me",
            "start": 38290,
            "end": 38450,
            "confidence": 0.9980469,
            "speaker": "B",
        },
        {
            "text": "ask",
            "start": 38450,
            "end": 38570,
            "confidence": 0.99902344,
            "speaker": "B",
        },
        {
            "text": "the",
            "start": 38570,
            "end": 38730,
            "confidence": 0.98339844,
            "speaker": "B",
        },
        {
            "text": "Vinceros,",
            "start": 38730,
            "end": 39810,
            "confidence": 0.8648437,
            "speaker": "B",
        },
        {
            "text": "how",
            "start": 41490,
            "end": 41850,
            "confidence": 1.0,
            "speaker": "B",
        },
        {
            "text": "did",
            "start": 41850,
            "end": 42210,
            "confidence": 0.9995117,
            "speaker": "B",
        },
        {
            "text": "Greg",
            "start": 43170,
            "end": 43610,
            "confidence": 0.8244629,
            "speaker": "B",
        },
        {
            "text": "wangle",
            "start": 43610,
            "end": 44130,
            "confidence": 0.9716797,
            "speaker": "B",
        },
        {
            "text": "you",
            "start": 44130,
            "end": 44370,
            "confidence": 0.99560547,
            "speaker": "B",
        },
        {
            "text": "into",
            "start": 44370,
            "end": 44610,
            "confidence": 0.99853516,
            "speaker": "B",
        },
        {
            "text": "this?",
            "start": 44610,
            "end": 44930,
            "confidence": 0.9995117,
            "speaker": "B",
        },
        {
            "text": "I",
            "start": 45970,
            "end": 46210,
            "confidence": 0.99658203,
            "speaker": "A",
        },
        {
            "text": "don't",
            "start": 46210,
            "end": 46410,
            "confidence": 0.9941406,
            "speaker": "A",
        },
        {
            "text": "really",
            "start": 46410,
            "end": 46610,
            "confidence": 0.97802734,
            "speaker": "A",
        },
        {
            "text": "think",
            "start": 46610,
            "end": 46810,
            "confidence": 0.99853516,
            "speaker": "A",
        },
        {
            "text": "he",
            "start": 46810,
            "end": 47010,
            "confidence": 0.9902344,
            "speaker": "A",
        },
        {
            "text": "really",
            "start": 47010,
            "end": 47330,
            "confidence": 0.98779297,
            "speaker": "A",
        },
        {
            "text": "wangled",
            "start": 47490,
            "end": 48050,
            "confidence": 0.9684245,
            "speaker": "A",
        },
        {
            "text": "us",
            "start": 48050,
            "end": 48250,
            "confidence": 0.97802734,
            "speaker": "A",
        },
        {
            "text": "early",
            "start": 48250,
            "end": 48490,
            "confidence": 0.24572754,
            "speaker": "A",
        },
        {
            "text": "into",
            "start": 48490,
            "end": 48730,
            "confidence": 0.95996094,
            "speaker": "A",
        },
        {
            "text": "it.",
            "start": 48730,
            "end": 48930,
            "confidence": 0.5239258,
            "speaker": "A",
        },
        {
            "text": "Well,",
            "start": 48930,
            "end": 49130,
            "confidence": 0.66308594,
            "speaker": "B",
        },
        {
            "text": "what",
            "start": 49130,
            "end": 49290,
            "confidence": 0.99902344,
            "speaker": "B",
        },
        {
            "text": "happened?",
            "start": 49290,
            "end": 49810,
            "confidence": 0.9992676,
            "speaker": "B",
        },
        {
            "text": "Well,",
            "start": 52610,
            "end": 52930,
            "confidence": 0.8173828,
            "speaker": "A",
        },
        {
            "text": "we",
            "start": 52930,
            "end": 53090,
            "confidence": 0.9995117,
            "speaker": "A",
        },
        {
            "text": "were",
            "start": 53090,
            "end": 53210,
            "confidence": 0.99853516,
            "speaker": "A",
        },
        {
            "text": "going",
            "start": 53210,
            "end": 53410,
            "confidence": 0.9848633,
            "speaker": "A",
        },
        {
            "text": "to",
            "start": 53410,
            "end": 53650,
            "confidence": 0.9980469,
            "speaker": "A",
        },
        {
            "text": "this",
            "start": 53650,
            "end": 53930,
            "confidence": 0.99853516,
            "speaker": "A",
        },
        {
            "text": "other",
            "start": 53930,
            "end": 54290,
            "confidence": 0.99902344,
            "speaker": "A",
        },
        {
            "text": "program",
            "start": 54290,
            "end": 54690,
            "confidence": 1.0,
            "speaker": "A",
        },
        {
            "text": "before",
            "start": 54690,
            "end": 55090,
            "confidence": 0.99609375,
            "speaker": "A",
        },
        {
            "text": "this",
            "start": 55090,
            "end": 55490,
            "confidence": 0.9970703,
            "speaker": "A",
        },
        {
            "text": "over",
            "start": 56290,
            "end": 56610,
            "confidence": 0.984375,
            "speaker": "A",
        },
        {
            "text": "at",
            "start": 56610,
            "end": 56810,
            "confidence": 0.9814453,
            "speaker": "A",
        },
        {
            "text": "the",
            "start": 56810,
            "end": 57090,
            "confidence": 0.9458008,
            "speaker": "A",
        },
        {
            "text": "stress",
            "start": 57330,
            "end": 57810,
            "confidence": 0.9472656,
            "speaker": "A",
        },
        {
            "text": "center,",
            "start": 57810,
            "end": 58290,
            "confidence": 0.9968262,
            "speaker": "A",
        },
        {
            "text": "and",
            "start": 59630,
            "end": 59870,
            "confidence": 0.98339844,
            "speaker": "A",
        },
        {
            "text": "I",
            "start": 63230,
            "end": 63510,
            "confidence": 0.99902344,
            "speaker": "A",
        },
        {
            "text": "guess",
            "start": 63510,
            "end": 63790,
            "confidence": 0.99975586,
            "speaker": "A",
        },
        {
            "text": "things",
            "start": 63790,
            "end": 64070,
            "confidence": 0.99853516,
            "speaker": "A",
        },
        {
            "text": "got",
            "start": 64070,
            "end": 64310,
            "confidence": 0.99560547,
            "speaker": "A",
        },
        {
            "text": "a",
            "start": 64310,
            "end": 64430,
            "confidence": 0.98339844,
            "speaker": "A",
        },
        {
            "text": "little",
            "start": 64430,
            "end": 64550,
            "confidence": 0.99853516,
            "speaker": "A",
        },
        {
            "text": "bit",
            "start": 64550,
            "end": 64790,
            "confidence": 0.98535156,
            "speaker": "A",
        },
        {
            "text": "hectical",
            "start": 64790,
            "end": 65350,
            "confidence": 0.98079425,
            "speaker": "A",
        },
        {
            "text": "or",
            "start": 65350,
            "end": 65590,
            "confidence": 0.99853516,
            "speaker": "A",
        },
        {
            "text": "something,",
            "start": 65590,
            "end": 65870,
            "confidence": 0.9301758,
            "speaker": "A",
        },
        {
            "text": "likely",
            "start": 66110,
            "end": 66510,
            "confidence": 0.6464844,
            "speaker": "A",
        },
        {
            "text": "by",
            "start": 68750,
            "end": 69110,
            "confidence": 0.72265625,
            "speaker": "A",
        },
        {
            "text": "them",
            "start": 69110,
            "end": 69390,
            "confidence": 0.9970703,
            "speaker": "A",
        },
        {
            "text": "wanting",
            "start": 69390,
            "end": 69750,
            "confidence": 0.9987793,
            "speaker": "A",
        },
        {
            "text": "us",
            "start": 69750,
            "end": 69910,
            "confidence": 0.99853516,
            "speaker": "A",
        },
        {
            "text": "to",
            "start": 69910,
            "end": 70070,
            "confidence": 0.99902344,
            "speaker": "A",
        },
        {
            "text": "come",
            "start": 70070,
            "end": 70310,
            "confidence": 0.9995117,
            "speaker": "A",
        },
        {
            "text": "there,",
            "start": 70310,
            "end": 70670,
            "confidence": 0.9975586,
            "speaker": "A",
        },
        {
            "text": "you",
            "start": 70670,
            "end": 70950,
            "confidence": 0.6743164,
            "speaker": "A",
        },
        {
            "text": "know,",
            "start": 70950,
            "end": 71150,
            "confidence": 0.73095703,
            "speaker": "A",
        },
        {
            "text": "at",
            "start": 71150,
            "end": 71430,
            "confidence": 0.98095703,
            "speaker": "A",
        },
        {
            "text": "certain",
            "start": 71430,
            "end": 71790,
            "confidence": 1.0,
            "speaker": "A",
        },
        {
            "text": "times",
            "start": 71790,
            "end": 72190,
            "confidence": 1.0,
            "speaker": "A",
        },
        {
            "text": "and",
            "start": 72190,
            "end": 72510,
            "confidence": 0.9916992,
            "speaker": "A",
        },
        {
            "text": "stuff.",
            "start": 72510,
            "end": 72870,
            "confidence": 0.9980469,
            "speaker": "A",
        },
        {
            "text": "And",
            "start": 72870,
            "end": 73230,
            "confidence": 0.8354492,
            "speaker": "A",
        },
        {
            "text": "they",
            "start": 74589,
            "end": 74990,
            "confidence": 0.9995117,
            "speaker": "A",
        },
        {
            "text": "sort",
            "start": 75150,
            "end": 75470,
            "confidence": 0.9991862,
            "speaker": "A",
        },
        {
            "text": "of",
            "start": 75470,
            "end": 75630,
            "confidence": 0.75390625,
            "speaker": "A",
        },
        {
            "text": "said",
            "start": 75630,
            "end": 75910,
            "confidence": 0.9995117,
            "speaker": "A",
        },
        {
            "text": "things",
            "start": 75910,
            "end": 76190,
            "confidence": 0.9995117,
            "speaker": "A",
        },
        {
            "text": "about",
            "start": 76190,
            "end": 76470,
            "confidence": 0.9995117,
            "speaker": "A",
        },
        {
            "text": "us",
            "start": 76470,
            "end": 76830,
            "confidence": 0.9995117,
            "speaker": "A",
        },
        {
            "text": "that",
            "start": 77710,
            "end": 78110,
            "confidence": 0.9970703,
            "speaker": "A",
        },
        {
            "text": "really",
            "start": 78270,
            "end": 78590,
            "confidence": 0.9995117,
            "speaker": "A",
        },
        {
            "text": "wasn't",
            "start": 78590,
            "end": 78950,
            "confidence": 0.9991455,
            "speaker": "A",
        },
        {
            "text": "even",
            "start": 78950,
            "end": 79150,
            "confidence": 0.9980469,
            "speaker": "A",
        },
        {
            "text": "true.",
            "start": 79150,
            "end": 79550,
            "confidence": 0.998291,
            "speaker": "A",
        },
        {
            "text": "They",
            "start": 80990,
            "end": 81390,
            "confidence": 0.9589844,
            "speaker": "A",
        },
        {
            "text": "were",
            "start": 81470,
            "end": 81790,
            "confidence": 0.99560547,
            "speaker": "A",
        },
        {
            "text": "saying",
            "start": 81790,
            "end": 82070,
            "confidence": 0.99902344,
            "speaker": "A",
        },
        {
            "text": "things",
            "start": 82070,
            "end": 82430,
            "confidence": 0.9995117,
            "speaker": "A",
        },
        {
            "text": "that",
            "start": 82430,
            "end": 82830,
            "confidence": 0.9868164,
            "speaker": "A",
        },
        {
            "text": "we",
            "start": 84430,
            "end": 84710,
            "confidence": 0.9975586,
            "speaker": "A",
        },
        {
            "text": "wasn't",
            "start": 84710,
            "end": 85030,
            "confidence": 0.99780273,
            "speaker": "A",
        },
        {
            "text": "coming",
            "start": 85030,
            "end": 85230,
            "confidence": 0.9272461,
            "speaker": "A",
        },
        {
            "text": "in",
            "start": 85230,
            "end": 85470,
            "confidence": 0.9980469,
            "speaker": "A",
        },
        {
            "text": "on",
            "start": 85470,
            "end": 85750,
            "confidence": 0.9980469,
            "speaker": "A",
        },
        {
            "text": "time,",
            "start": 85750,
            "end": 86110,
            "confidence": 1.0,
            "speaker": "A",
        },
        {
            "text": "we",
            "start": 87150,
            "end": 87430,
            "confidence": 0.99658203,
            "speaker": "A",
        },
        {
            "text": "wasn't",
            "start": 87430,
            "end": 87750,
            "confidence": 0.9949951,
            "speaker": "A",
        },
        {
            "text": "doing",
            "start": 87750,
            "end": 87990,
            "confidence": 0.9375,
            "speaker": "A",
        },
        {
            "text": "these",
            "start": 87990,
            "end": 88270,
            "confidence": 0.99853516,
            "speaker": "A",
        },
        {
            "text": "things",
            "start": 88270,
            "end": 88550,
            "confidence": 0.99902344,
            "speaker": "A",
        },
        {
            "text": "right",
            "start": 88550,
            "end": 88910,
            "confidence": 0.99902344,
            "speaker": "A",
        },
        {
            "text": "when",
            "start": 88990,
            "end": 89270,
            "confidence": 0.98828125,
            "speaker": "A",
        },
        {
            "text": "we",
            "start": 89270,
            "end": 89430,
            "confidence": 0.9980469,
            "speaker": "A",
        },
        {
            "text": "were",
            "start": 89430,
            "end": 89630,
            "confidence": 0.9970703,
            "speaker": "A",
        },
        {
            "text": "there,",
            "start": 89630,
            "end": 89950,
            "confidence": 0.9970703,
            "speaker": "A",
        },
        {
            "text": "wasn't",
            "start": 90650,
            "end": 90930,
            "confidence": 0.9803467,
            "speaker": "A",
        },
        {
            "text": "taking",
            "start": 90930,
            "end": 91170,
            "confidence": 0.94677734,
            "speaker": "A",
        },
        {
            "text": "care",
            "start": 91170,
            "end": 91410,
            "confidence": 0.9995117,
            "speaker": "A",
        },
        {
            "text": "of",
            "start": 91410,
            "end": 91530,
            "confidence": 0.99853516,
            "speaker": "A",
        },
        {
            "text": "the",
            "start": 91530,
            "end": 91650,
            "confidence": 0.99902344,
            "speaker": "A",
        },
        {
            "text": "baby.",
            "start": 91650,
            "end": 92010,
            "confidence": 1.0,
            "speaker": "A",
        },
        {
            "text": "Right",
            "start": 92010,
            "end": 92250,
            "confidence": 0.99853516,
            "speaker": "A",
        },
        {
            "text": "this",
            "start": 92250,
            "end": 92490,
            "confidence": 0.99902344,
            "speaker": "A",
        },
        {
            "text": "way.",
            "start": 92490,
            "end": 92810,
            "confidence": 0.97802734,
            "speaker": "A",
        },
        {
            "text": "How",
            "start": 94570,
            "end": 94850,
            "confidence": 0.99902344,
            "speaker": "B",
        },
        {
            "text": "long",
            "start": 94850,
            "end": 95050,
            "confidence": 1.0,
            "speaker": "B",
        },
        {
            "text": "did",
            "start": 95050,
            "end": 95250,
            "confidence": 1.0,
            "speaker": "B",
        },
        {
            "text": "you",
            "start": 95250,
            "end": 95370,
            "confidence": 0.99902344,
            "speaker": "B",
        },
        {
            "text": "go",
            "start": 95370,
            "end": 95530,
            "confidence": 0.9995117,
            "speaker": "B",
        },
        {
            "text": "there",
            "start": 95530,
            "end": 95850,
            "confidence": 0.9995117,
            "speaker": "B",
        },
        {
            "text": "before",
            "start": 95850,
            "end": 96170,
            "confidence": 1.0,
            "speaker": "B",
        },
        {
            "text": "you",
            "start": 96170,
            "end": 96370,
            "confidence": 0.98535156,
            "speaker": "B",
        },
        {
            "text": "came",
            "start": 96370,
            "end": 96570,
            "confidence": 1.0,
            "speaker": "B",
        },
        {
            "text": "here?",
            "start": 96570,
            "end": 96890,
            "confidence": 1.0,
            "speaker": "B",
        },
        {
            "text": "What",
            "start": 98330,
            "end": 98570,
            "confidence": 0.97558594,
            "speaker": "A",
        },
        {
            "text": "would",
            "start": 98570,
            "end": 98690,
            "confidence": 0.99365234,
            "speaker": "A",
        },
        {
            "text": "you",
            "start": 98690,
            "end": 98850,
            "confidence": 0.9970703,
            "speaker": "A",
        },
        {
            "text": "say?",
            "start": 98850,
            "end": 99130,
            "confidence": 0.99902344,
            "speaker": "A",
        },
        {
            "text": "About",
            "start": 100410,
            "end": 100730,
            "confidence": 0.9941406,
            "speaker": "B",
        },
        {
            "text": "a",
            "start": 100730,
            "end": 100930,
            "confidence": 0.9980469,
            "speaker": "B",
        },
        {
            "text": "month?",
            "start": 100930,
            "end": 101210,
            "confidence": 0.9995117,
            "speaker": "B",
        },
        {
            "text": "About",
            "start": 101530,
            "end": 101890,
            "confidence": 0.9902344,
            "speaker": "A",
        },
        {
            "text": "a",
            "start": 101890,
            "end": 102090,
            "confidence": 0.99902344,
            "speaker": "A",
        },
        {
            "text": "month.",
            "start": 102090,
            "end": 102330,
            "confidence": 1.0,
            "speaker": "A",
        },
        {
            "text": "And",
            "start": 103290,
            "end": 103570,
            "confidence": 0.93603516,
            "speaker": "B",
        },
        {
            "text": "then.",
            "start": 103570,
            "end": 103850,
            "confidence": 0.99072266,
            "speaker": "B",
        },
        {
            "text": "So",
            "start": 104010,
            "end": 104330,
            "confidence": 0.98828125,
            "speaker": "B",
        },
        {
            "text": "you",
            "start": 104330,
            "end": 104530,
            "confidence": 1.0,
            "speaker": "B",
        },
        {
            "text": "were",
            "start": 104530,
            "end": 104730,
            "confidence": 0.9995117,
            "speaker": "B",
        },
        {
            "text": "referred",
            "start": 104730,
            "end": 105370,
            "confidence": 0.91829425,
            "speaker": "B",
        },
        {
            "text": "here",
            "start": 105370,
            "end": 105690,
            "confidence": 1.0,
            "speaker": "B",
        },
        {
            "text": "or",
            "start": 105690,
            "end": 105970,
            "confidence": 0.9946289,
            "speaker": "B",
        },
        {
            "text": "you",
            "start": 105970,
            "end": 106170,
            "confidence": 0.9975586,
            "speaker": "B",
        },
        {
            "text": "found",
            "start": 106170,
            "end": 106490,
            "confidence": 0.9921875,
            "speaker": "B",
        },
        {
            "text": "this",
            "start": 106570,
            "end": 106890,
            "confidence": 0.9995117,
            "speaker": "B",
        },
        {
            "text": "place?",
            "start": 106890,
            "end": 107210,
            "confidence": 1.0,
            "speaker": "B",
        },
        {
            "text": "We",
            "start": 107530,
            "end": 107770,
            "confidence": 0.9975586,
            "speaker": "B",
        },
        {
            "text": "were",
            "start": 107770,
            "end": 107890,
            "confidence": 0.99853516,
            "speaker": "B",
        },
        {
            "text": "referred",
            "start": 107890,
            "end": 108290,
            "confidence": 0.9995117,
            "speaker": "B",
        },
        {
            "text": "here",
            "start": 108290,
            "end": 108570,
            "confidence": 0.9921875,
            "speaker": "B",
        },
        {
            "text": "by",
            "start": 108810,
            "end": 109210,
            "confidence": 0.99609375,
            "speaker": "B",
        },
        {
            "text": "what",
            "start": 109370,
            "end": 109770,
            "confidence": 0.97509766,
            "speaker": "B",
        },
        {
            "text": "court?",
            "start": 110250,
            "end": 110650,
            "confidence": 0.76416016,
            "speaker": "B",
        },
    ],
    "utterances": [
        {
            "speaker": "B",
            "text": "I'm Dr. Murray Boyne. This group today includes Greg Sashkin, who's the therapist, and Mr. John Vinceguero and Mrs. Anita Vinceguero. And if I hear. Let me ask the Vinceros, how did Greg wangle you into this?",
            "confidence": 0.93395364,
            "start": 17520,
            "end": 44930,
            "words": [
                {
                    "text": "I'm",
                    "start": 17520,
                    "end": 17720,
                    "confidence": 0.9609375,
                    "speaker": "B",
                },
                {
                    "text": "Dr.",
                    "start": 17720,
                    "end": 17960,
                    "confidence": 0.98828,
                    "speaker": "B",
                },
                {
                    "text": "Murray",
                    "start": 17960,
                    "end": 18360,
                    "confidence": 0.8414714,
                    "speaker": "B",
                },
                {
                    "text": "Boyne.",
                    "start": 18360,
                    "end": 18960,
                    "confidence": 0.6133626,
                    "speaker": "B",
                },
                {
                    "text": "This",
                    "start": 20000,
                    "end": 20320,
                    "confidence": 0.9785156,
                    "speaker": "B",
                },
                {
                    "text": "group",
                    "start": 20320,
                    "end": 20600,
                    "confidence": 0.99902344,
                    "speaker": "B",
                },
                {
                    "text": "today",
                    "start": 20600,
                    "end": 20960,
                    "confidence": 0.9921875,
                    "speaker": "B",
                },
                {
                    "text": "includes",
                    "start": 20960,
                    "end": 21760,
                    "confidence": 0.9914551,
                    "speaker": "B",
                },
                {
                    "text": "Greg",
                    "start": 23200,
                    "end": 23600,
                    "confidence": 0.98828125,
                    "speaker": "B",
                },
                {
                    "text": "Sashkin,",
                    "start": 23600,
                    "end": 24480,
                    "confidence": 0.9473877,
                    "speaker": "B",
                },
                {
                    "text": "who's",
                    "start": 24800,
                    "end": 25240,
                    "confidence": 0.90722656,
                    "speaker": "B",
                },
                {
                    "text": "the",
                    "start": 25240,
                    "end": 25400,
                    "confidence": 0.9951172,
                    "speaker": "B",
                },
                {
                    "text": "therapist,",
                    "start": 25400,
                    "end": 26000,
                    "confidence": 0.99609375,
                    "speaker": "B",
                },
                {
                    "text": "and",
                    "start": 27330,
                    "end": 27570,
                    "confidence": 0.9550781,
                    "speaker": "B",
                },
                {
                    "text": "Mr.",
                    "start": 29250,
                    "end": 29690,
                    "confidence": 0.99951,
                    "speaker": "B",
                },
                {
                    "text": "John",
                    "start": 29690,
                    "end": 30050,
                    "confidence": 0.99365234,
                    "speaker": "B",
                },
                {
                    "text": "Vinceguero",
                    "start": 30050,
                    "end": 31010,
                    "confidence": 0.8442383,
                    "speaker": "B",
                },
                {
                    "text": "and",
                    "start": 31170,
                    "end": 31530,
                    "confidence": 0.7055664,
                    "speaker": "B",
                },
                {
                    "text": "Mrs.",
                    "start": 31530,
                    "end": 32050,
                    "confidence": 0.99487,
                    "speaker": "B",
                },
                {
                    "text": "Anita",
                    "start": 32050,
                    "end": 32850,
                    "confidence": 0.8515625,
                    "speaker": "B",
                },
                {
                    "text": "Vinceguero.",
                    "start": 32850,
                    "end": 33810,
                    "confidence": 0.85148114,
                    "speaker": "B",
                },
                {
                    "text": "And",
                    "start": 36690,
                    "end": 37010,
                    "confidence": 0.59375,
                    "speaker": "B",
                },
                {
                    "text": "if",
                    "start": 37010,
                    "end": 37250,
                    "confidence": 0.9975586,
                    "speaker": "B",
                },
                {
                    "text": "I",
                    "start": 37250,
                    "end": 37450,
                    "confidence": 0.9995117,
                    "speaker": "B",
                },
                {
                    "text": "hear.",
                    "start": 37450,
                    "end": 37730,
                    "confidence": 0.9868164,
                    "speaker": "B",
                },
                {
                    "text": "Let",
                    "start": 37970,
                    "end": 38290,
                    "confidence": 0.94873047,
                    "speaker": "B",
                },
                {
                    "text": "me",
                    "start": 38290,
                    "end": 38450,
                    "confidence": 0.9980469,
                    "speaker": "B",
                },
                {
                    "text": "ask",
                    "start": 38450,
                    "end": 38570,
                    "confidence": 0.99902344,
                    "speaker": "B",
                },
                {
                    "text": "the",
                    "start": 38570,
                    "end": 38730,
                    "confidence": 0.98339844,
                    "speaker": "B",
                },
                {
                    "text": "Vinceros,",
                    "start": 38730,
                    "end": 39810,
                    "confidence": 0.8648437,
                    "speaker": "B",
                },
                {
                    "text": "how",
                    "start": 41490,
                    "end": 41850,
                    "confidence": 1.0,
                    "speaker": "B",
                },
                {
                    "text": "did",
                    "start": 41850,
                    "end": 42210,
                    "confidence": 0.9995117,
                    "speaker": "B",
                },
                {
                    "text": "Greg",
                    "start": 43170,
                    "end": 43610,
                    "confidence": 0.8244629,
                    "speaker": "B",
                },
                {
                    "text": "wangle",
                    "start": 43610,
                    "end": 44130,
                    "confidence": 0.9716797,
                    "speaker": "B",
                },
                {
                    "text": "you",
                    "start": 44130,
                    "end": 44370,
                    "confidence": 0.99560547,
                    "speaker": "B",
                },
                {
                    "text": "into",
                    "start": 44370,
                    "end": 44610,
                    "confidence": 0.99853516,
                    "speaker": "B",
                },
                {
                    "text": "this?",
                    "start": 44610,
                    "end": 44930,
                    "confidence": 0.9995117,
                    "speaker": "B",
                },
            ],
        },
        {
            "speaker": "A",
            "text": "I don't really think he really wangled us early into it.",
            "confidence": 0.8746708,
            "start": 45970,
            "end": 48930,
            "words": [
                {
                    "text": "I",
                    "start": 45970,
                    "end": 46210,
                    "confidence": 0.99658203,
                    "speaker": "A",
                },
                {
                    "text": "don't",
                    "start": 46210,
                    "end": 46410,
                    "confidence": 0.9941406,
                    "speaker": "A",
                },
                {
                    "text": "really",
                    "start": 46410,
                    "end": 46610,
                    "confidence": 0.97802734,
                    "speaker": "A",
                },
                {
                    "text": "think",
                    "start": 46610,
                    "end": 46810,
                    "confidence": 0.99853516,
                    "speaker": "A",
                },
                {
                    "text": "he",
                    "start": 46810,
                    "end": 47010,
                    "confidence": 0.9902344,
                    "speaker": "A",
                },
                {
                    "text": "really",
                    "start": 47010,
                    "end": 47330,
                    "confidence": 0.98779297,
                    "speaker": "A",
                },
                {
                    "text": "wangled",
                    "start": 47490,
                    "end": 48050,
                    "confidence": 0.9684245,
                    "speaker": "A",
                },
                {
                    "text": "us",
                    "start": 48050,
                    "end": 48250,
                    "confidence": 0.97802734,
                    "speaker": "A",
                },
                {
                    "text": "early",
                    "start": 48250,
                    "end": 48490,
                    "confidence": 0.24572754,
                    "speaker": "A",
                },
                {
                    "text": "into",
                    "start": 48490,
                    "end": 48730,
                    "confidence": 0.95996094,
                    "speaker": "A",
                },
                {
                    "text": "it.",
                    "start": 48730,
                    "end": 48930,
                    "confidence": 0.5239258,
                    "speaker": "A",
                },
            ],
        },
        {
            "speaker": "B",
            "text": "Well, what happened?",
            "confidence": 0.8871257,
            "start": 48930,
            "end": 49810,
            "words": [
                {
                    "text": "Well,",
                    "start": 48930,
                    "end": 49130,
                    "confidence": 0.66308594,
                    "speaker": "B",
                },
                {
                    "text": "what",
                    "start": 49130,
                    "end": 49290,
                    "confidence": 0.99902344,
                    "speaker": "B",
                },
                {
                    "text": "happened?",
                    "start": 49290,
                    "end": 49810,
                    "confidence": 0.9992676,
                    "speaker": "B",
                },
            ],
        },
        {
            "speaker": "A",
            "text": "Well, we were going to this other program before this over at the stress center, and I guess things got a little bit hectical or something, likely by them wanting us to come there, you know, at certain times and stuff. And they sort of said things about us that really wasn't even true. They were saying things that we wasn't coming in on time, we wasn't doing these things right when we were there, wasn't taking care of the baby. Right this way.",
            "confidence": 0.9699547,
            "start": 52610,
            "end": 92810,
            "words": [
                {
                    "text": "Well,",
                    "start": 52610,
                    "end": 52930,
                    "confidence": 0.8173828,
                    "speaker": "A",
                },
                {
                    "text": "we",
                    "start": 52930,
                    "end": 53090,
                    "confidence": 0.9995117,
                    "speaker": "A",
                },
                {
                    "text": "were",
                    "start": 53090,
                    "end": 53210,
                    "confidence": 0.99853516,
                    "speaker": "A",
                },
                {
                    "text": "going",
                    "start": 53210,
                    "end": 53410,
                    "confidence": 0.9848633,
                    "speaker": "A",
                },
                {
                    "text": "to",
                    "start": 53410,
                    "end": 53650,
                    "confidence": 0.9980469,
                    "speaker": "A",
                },
                {
                    "text": "this",
                    "start": 53650,
                    "end": 53930,
                    "confidence": 0.99853516,
                    "speaker": "A",
                },
                {
                    "text": "other",
                    "start": 53930,
                    "end": 54290,
                    "confidence": 0.99902344,
                    "speaker": "A",
                },
                {
                    "text": "program",
                    "start": 54290,
                    "end": 54690,
                    "confidence": 1.0,
                    "speaker": "A",
                },
                {
                    "text": "before",
                    "start": 54690,
                    "end": 55090,
                    "confidence": 0.99609375,
                    "speaker": "A",
                },
                {
                    "text": "this",
                    "start": 55090,
                    "end": 55490,
                    "confidence": 0.9970703,
                    "speaker": "A",
                },
                {
                    "text": "over",
                    "start": 56290,
                    "end": 56610,
                    "confidence": 0.984375,
                    "speaker": "A",
                },
                {
                    "text": "at",
                    "start": 56610,
                    "end": 56810,
                    "confidence": 0.9814453,
                    "speaker": "A",
                },
                {
                    "text": "the",
                    "start": 56810,
                    "end": 57090,
                    "confidence": 0.9458008,
                    "speaker": "A",
                },
                {
                    "text": "stress",
                    "start": 57330,
                    "end": 57810,
                    "confidence": 0.9472656,
                    "speaker": "A",
                },
                {
                    "text": "center,",
                    "start": 57810,
                    "end": 58290,
                    "confidence": 0.9968262,
                    "speaker": "A",
                },
                {
                    "text": "and",
                    "start": 59630,
                    "end": 59870,
                    "confidence": 0.98339844,
                    "speaker": "A",
                },
                {
                    "text": "I",
                    "start": 63230,
                    "end": 63510,
                    "confidence": 0.99902344,
                    "speaker": "A",
                },
                {
                    "text": "guess",
                    "start": 63510,
                    "end": 63790,
                    "confidence": 0.99975586,
                    "speaker": "A",
                },
                {
                    "text": "things",
                    "start": 63790,
                    "end": 64070,
                    "confidence": 0.99853516,
                    "speaker": "A",
                },
                {
                    "text": "got",
                    "start": 64070,
                    "end": 64310,
                    "confidence": 0.99560547,
                    "speaker": "A",
                },
                {
                    "text": "a",
                    "start": 64310,
                    "end": 64430,
                    "confidence": 0.98339844,
                    "speaker": "A",
                },
                {
                    "text": "little",
                    "start": 64430,
                    "end": 64550,
                    "confidence": 0.99853516,
                    "speaker": "A",
                },
                {
                    "text": "bit",
                    "start": 64550,
                    "end": 64790,
                    "confidence": 0.98535156,
                    "speaker": "A",
                },
                {
                    "text": "hectical",
                    "start": 64790,
                    "end": 65350,
                    "confidence": 0.98079425,
                    "speaker": "A",
                },
                {
                    "text": "or",
                    "start": 65350,
                    "end": 65590,
                    "confidence": 0.99853516,
                    "speaker": "A",
                },
                {
                    "text": "something,",
                    "start": 65590,
                    "end": 65870,
                    "confidence": 0.9301758,
                    "speaker": "A",
                },
                {
                    "text": "likely",
                    "start": 66110,
                    "end": 66510,
                    "confidence": 0.6464844,
                    "speaker": "A",
                },
                {
                    "text": "by",
                    "start": 68750,
                    "end": 69110,
                    "confidence": 0.72265625,
                    "speaker": "A",
                },
                {
                    "text": "them",
                    "start": 69110,
                    "end": 69390,
                    "confidence": 0.9970703,
                    "speaker": "A",
                },
                {
                    "text": "wanting",
                    "start": 69390,
                    "end": 69750,
                    "confidence": 0.9987793,
                    "speaker": "A",
                },
                {
                    "text": "us",
                    "start": 69750,
                    "end": 69910,
                    "confidence": 0.99853516,
                    "speaker": "A",
                },
                {
                    "text": "to",
                    "start": 69910,
                    "end": 70070,
                    "confidence": 0.99902344,
                    "speaker": "A",
                },
                {
                    "text": "come",
                    "start": 70070,
                    "end": 70310,
                    "confidence": 0.9995117,
                    "speaker": "A",
                },
                {
                    "text": "there,",
                    "start": 70310,
                    "end": 70670,
                    "confidence": 0.9975586,
                    "speaker": "A",
                },
                {
                    "text": "you",
                    "start": 70670,
                    "end": 70950,
                    "confidence": 0.6743164,
                    "speaker": "A",
                },
                {
                    "text": "know,",
                    "start": 70950,
                    "end": 71150,
                    "confidence": 0.73095703,
                    "speaker": "A",
                },
                {
                    "text": "at",
                    "start": 71150,
                    "end": 71430,
                    "confidence": 0.98095703,
                    "speaker": "A",
                },
                {
                    "text": "certain",
                    "start": 71430,
                    "end": 71790,
                    "confidence": 1.0,
                    "speaker": "A",
                },
                {
                    "text": "times",
                    "start": 71790,
                    "end": 72190,
                    "confidence": 1.0,
                    "speaker": "A",
                },
                {
                    "text": "and",
                    "start": 72190,
                    "end": 72510,
                    "confidence": 0.9916992,
                    "speaker": "A",
                },
                {
                    "text": "stuff.",
                    "start": 72510,
                    "end": 72870,
                    "confidence": 0.9980469,
                    "speaker": "A",
                },
                {
                    "text": "And",
                    "start": 72870,
                    "end": 73230,
                    "confidence": 0.8354492,
                    "speaker": "A",
                },
                {
                    "text": "they",
                    "start": 74589,
                    "end": 74990,
                    "confidence": 0.9995117,
                    "speaker": "A",
                },
                {
                    "text": "sort",
                    "start": 75150,
                    "end": 75470,
                    "confidence": 0.9991862,
                    "speaker": "A",
                },
                {
                    "text": "of",
                    "start": 75470,
                    "end": 75630,
                    "confidence": 0.75390625,
                    "speaker": "A",
                },
                {
                    "text": "said",
                    "start": 75630,
                    "end": 75910,
                    "confidence": 0.9995117,
                    "speaker": "A",
                },
                {
                    "text": "things",
                    "start": 75910,
                    "end": 76190,
                    "confidence": 0.9995117,
                    "speaker": "A",
                },
                {
                    "text": "about",
                    "start": 76190,
                    "end": 76470,
                    "confidence": 0.9995117,
                    "speaker": "A",
                },
                {
                    "text": "us",
                    "start": 76470,
                    "end": 76830,
                    "confidence": 0.9995117,
                    "speaker": "A",
                },
                {
                    "text": "that",
                    "start": 77710,
                    "end": 78110,
                    "confidence": 0.9970703,
                    "speaker": "A",
                },
                {
                    "text": "really",
                    "start": 78270,
                    "end": 78590,
                    "confidence": 0.9995117,
                    "speaker": "A",
                },
                {
                    "text": "wasn't",
                    "start": 78590,
                    "end": 78950,
                    "confidence": 0.9991455,
                    "speaker": "A",
                },
                {
                    "text": "even",
                    "start": 78950,
                    "end": 79150,
                    "confidence": 0.9980469,
                    "speaker": "A",
                },
                {
                    "text": "true.",
                    "start": 79150,
                    "end": 79550,
                    "confidence": 0.998291,
                    "speaker": "A",
                },
                {
                    "text": "They",
                    "start": 80990,
                    "end": 81390,
                    "confidence": 0.9589844,
                    "speaker": "A",
                },
                {
                    "text": "were",
                    "start": 81470,
                    "end": 81790,
                    "confidence": 0.99560547,
                    "speaker": "A",
                },
                {
                    "text": "saying",
                    "start": 81790,
                    "end": 82070,
                    "confidence": 0.99902344,
                    "speaker": "A",
                },
                {
                    "text": "things",
                    "start": 82070,
                    "end": 82430,
                    "confidence": 0.9995117,
                    "speaker": "A",
                },
                {
                    "text": "that",
                    "start": 82430,
                    "end": 82830,
                    "confidence": 0.9868164,
                    "speaker": "A",
                },
                {
                    "text": "we",
                    "start": 84430,
                    "end": 84710,
                    "confidence": 0.9975586,
                    "speaker": "A",
                },
                {
                    "text": "wasn't",
                    "start": 84710,
                    "end": 85030,
                    "confidence": 0.99780273,
                    "speaker": "A",
                },
                {
                    "text": "coming",
                    "start": 85030,
                    "end": 85230,
                    "confidence": 0.9272461,
                    "speaker": "A",
                },
                {
                    "text": "in",
                    "start": 85230,
                    "end": 85470,
                    "confidence": 0.9980469,
                    "speaker": "A",
                },
                {
                    "text": "on",
                    "start": 85470,
                    "end": 85750,
                    "confidence": 0.9980469,
                    "speaker": "A",
                },
                {
                    "text": "time,",
                    "start": 85750,
                    "end": 86110,
                    "confidence": 1.0,
                    "speaker": "A",
                },
                {
                    "text": "we",
                    "start": 87150,
                    "end": 87430,
                    "confidence": 0.99658203,
                    "speaker": "A",
                },
                {
                    "text": "wasn't",
                    "start": 87430,
                    "end": 87750,
                    "confidence": 0.9949951,
                    "speaker": "A",
                },
                {
                    "text": "doing",
                    "start": 87750,
                    "end": 87990,
                    "confidence": 0.9375,
                    "speaker": "A",
                },
                {
                    "text": "these",
                    "start": 87990,
                    "end": 88270,
                    "confidence": 0.99853516,
                    "speaker": "A",
                },
                {
                    "text": "things",
                    "start": 88270,
                    "end": 88550,
                    "confidence": 0.99902344,
                    "speaker": "A",
                },
                {
                    "text": "right",
                    "start": 88550,
                    "end": 88910,
                    "confidence": 0.99902344,
                    "speaker": "A",
                },
                {
                    "text": "when",
                    "start": 88990,
                    "end": 89270,
                    "confidence": 0.98828125,
                    "speaker": "A",
                },
                {
                    "text": "we",
                    "start": 89270,
                    "end": 89430,
                    "confidence": 0.9980469,
                    "speaker": "A",
                },
                {
                    "text": "were",
                    "start": 89430,
                    "end": 89630,
                    "confidence": 0.9970703,
                    "speaker": "A",
                },
                {
                    "text": "there,",
                    "start": 89630,
                    "end": 89950,
                    "confidence": 0.9970703,
                    "speaker": "A",
                },
                {
                    "text": "wasn't",
                    "start": 90650,
                    "end": 90930,
                    "confidence": 0.9803467,
                    "speaker": "A",
                },
                {
                    "text": "taking",
                    "start": 90930,
                    "end": 91170,
                    "confidence": 0.94677734,
                    "speaker": "A",
                },
                {
                    "text": "care",
                    "start": 91170,
                    "end": 91410,
                    "confidence": 0.9995117,
                    "speaker": "A",
                },
                {
                    "text": "of",
                    "start": 91410,
                    "end": 91530,
                    "confidence": 0.99853516,
                    "speaker": "A",
                },
                {
                    "text": "the",
                    "start": 91530,
                    "end": 91650,
                    "confidence": 0.99902344,
                    "speaker": "A",
                },
                {
                    "text": "baby.",
                    "start": 91650,
                    "end": 92010,
                    "confidence": 1.0,
                    "speaker": "A",
                },
                {
                    "text": "Right",
                    "start": 92010,
                    "end": 92250,
                    "confidence": 0.99853516,
                    "speaker": "A",
                },
                {
                    "text": "this",
                    "start": 92250,
                    "end": 92490,
                    "confidence": 0.99902344,
                    "speaker": "A",
                },
                {
                    "text": "way.",
                    "start": 92490,
                    "end": 92810,
                    "confidence": 0.97802734,
                    "speaker": "A",
                },
            ],
        },
        {
            "speaker": "B",
            "text": "How long did you go there before you came here?",
            "confidence": 0.9982422,
            "start": 94570,
            "end": 96890,
            "words": [
                {
                    "text": "How",
                    "start": 94570,
                    "end": 94850,
                    "confidence": 0.99902344,
                    "speaker": "B",
                },
                {
                    "text": "long",
                    "start": 94850,
                    "end": 95050,
                    "confidence": 1.0,
                    "speaker": "B",
                },
                {
                    "text": "did",
                    "start": 95050,
                    "end": 95250,
                    "confidence": 1.0,
                    "speaker": "B",
                },
                {
                    "text": "you",
                    "start": 95250,
                    "end": 95370,
                    "confidence": 0.99902344,
                    "speaker": "B",
                },
                {
                    "text": "go",
                    "start": 95370,
                    "end": 95530,
                    "confidence": 0.9995117,
                    "speaker": "B",
                },
                {
                    "text": "there",
                    "start": 95530,
                    "end": 95850,
                    "confidence": 0.9995117,
                    "speaker": "B",
                },
                {
                    "text": "before",
                    "start": 95850,
                    "end": 96170,
                    "confidence": 1.0,
                    "speaker": "B",
                },
                {
                    "text": "you",
                    "start": 96170,
                    "end": 96370,
                    "confidence": 0.98535156,
                    "speaker": "B",
                },
                {
                    "text": "came",
                    "start": 96370,
                    "end": 96570,
                    "confidence": 1.0,
                    "speaker": "B",
                },
                {
                    "text": "here?",
                    "start": 96570,
                    "end": 96890,
                    "confidence": 1.0,
                    "speaker": "B",
                },
            ],
        },
        {
            "speaker": "A",
            "text": "What would you say?",
            "confidence": 0.991333,
            "start": 98330,
            "end": 99130,
            "words": [
                {
                    "text": "What",
                    "start": 98330,
                    "end": 98570,
                    "confidence": 0.97558594,
                    "speaker": "A",
                },
                {
                    "text": "would",
                    "start": 98570,
                    "end": 98690,
                    "confidence": 0.99365234,
                    "speaker": "A",
                },
                {
                    "text": "you",
                    "start": 98690,
                    "end": 98850,
                    "confidence": 0.9970703,
                    "speaker": "A",
                },
                {
                    "text": "say?",
                    "start": 98850,
                    "end": 99130,
                    "confidence": 0.99902344,
                    "speaker": "A",
                },
            ],
        },
        {
            "speaker": "B",
            "text": "About a month?",
            "confidence": 0.9972331,
            "start": 100410,
            "end": 101210,
            "words": [
                {
                    "text": "About",
                    "start": 100410,
                    "end": 100730,
                    "confidence": 0.9941406,
                    "speaker": "B",
                },
                {
                    "text": "a",
                    "start": 100730,
                    "end": 100930,
                    "confidence": 0.9980469,
                    "speaker": "B",
                },
                {
                    "text": "month?",
                    "start": 100930,
                    "end": 101210,
                    "confidence": 0.9995117,
                    "speaker": "B",
                },
            ],
        },
        {
            "speaker": "A",
            "text": "About a month.",
            "confidence": 0.99641925,
            "start": 101530,
            "end": 102330,
            "words": [
                {
                    "text": "About",
                    "start": 101530,
                    "end": 101890,
                    "confidence": 0.9902344,
                    "speaker": "A",
                },
                {
                    "text": "a",
                    "start": 101890,
                    "end": 102090,
                    "confidence": 0.99902344,
                    "speaker": "A",
                },
                {
                    "text": "month.",
                    "start": 102090,
                    "end": 102330,
                    "confidence": 1.0,
                    "speaker": "A",
                },
            ],
        },
        {
            "speaker": "B",
            "text": "And then. So you were referred here or you found this place? We were referred here by what court?",
            "confidence": 0.975783,
            "start": 103290,
            "end": 110650,
            "words": [
                {
                    "text": "And",
                    "start": 103290,
                    "end": 103570,
                    "confidence": 0.93603516,
                    "speaker": "B",
                },
                {
                    "text": "then.",
                    "start": 103570,
                    "end": 103850,
                    "confidence": 0.99072266,
                    "speaker": "B",
                },
                {
                    "text": "So",
                    "start": 104010,
                    "end": 104330,
                    "confidence": 0.98828125,
                    "speaker": "B",
                },
                {
                    "text": "you",
                    "start": 104330,
                    "end": 104530,
                    "confidence": 1.0,
                    "speaker": "B",
                },
                {
                    "text": "were",
                    "start": 104530,
                    "end": 104730,
                    "confidence": 0.9995117,
                    "speaker": "B",
                },
                {
                    "text": "referred",
                    "start": 104730,
                    "end": 105370,
                    "confidence": 0.91829425,
                    "speaker": "B",
                },
                {
                    "text": "here",
                    "start": 105370,
                    "end": 105690,
                    "confidence": 1.0,
                    "speaker": "B",
                },
                {
                    "text": "or",
                    "start": 105690,
                    "end": 105970,
                    "confidence": 0.9946289,
                    "speaker": "B",
                },
                {
                    "text": "you",
                    "start": 105970,
                    "end": 106170,
                    "confidence": 0.9975586,
                    "speaker": "B",
                },
                {
                    "text": "found",
                    "start": 106170,
                    "end": 106490,
                    "confidence": 0.9921875,
                    "speaker": "B",
                },
                {
                    "text": "this",
                    "start": 106570,
                    "end": 106890,
                    "confidence": 0.9995117,
                    "speaker": "B",
                },
                {
                    "text": "place?",
                    "start": 106890,
                    "end": 107210,
                    "confidence": 1.0,
                    "speaker": "B",
                },
                {
                    "text": "We",
                    "start": 107530,
                    "end": 107770,
                    "confidence": 0.9975586,
                    "speaker": "B",
                },
                {
                    "text": "were",
                    "start": 107770,
                    "end": 107890,
                    "confidence": 0.99853516,
                    "speaker": "B",
                },
                {
                    "text": "referred",
                    "start": 107890,
                    "end": 108290,
                    "confidence": 0.9995117,
                    "speaker": "B",
                },
                {
                    "text": "here",
                    "start": 108290,
                    "end": 108570,
                    "confidence": 0.9921875,
                    "speaker": "B",
                },
                {
                    "text": "by",
                    "start": 108810,
                    "end": 109210,
                    "confidence": 0.99609375,
                    "speaker": "B",
                },
                {
                    "text": "what",
                    "start": 109370,
                    "end": 109770,
                    "confidence": 0.97509766,
                    "speaker": "B",
                },
                {
                    "text": "court?",
                    "start": 110250,
                    "end": 110650,
                    "confidence": 0.76416016,
                    "speaker": "B",
                },
            ],
        },
    ],
    "confidence": 0.95852774,
    "audio_duration": 112,
    "punctuate": True,
    "format_text": True,
    "dual_channel": False,
    "webhook_url": None,
    "webhook_status_code": None,
    "webhook_auth": False,
    "webhook_auth_header_name": None,
    "speed_boost": False,
    "auto_highlights_result": None,
    "auto_highlights": False,
    "audio_start_from": None,
    "audio_end_at": None,
    "word_boost": [],
    "boost_param": None,
    "prompt": None,
    "keyterms_prompt": [],
    "filter_profanity": False,
    "redact_pii": False,
    "redact_pii_audio": False,
    "redact_pii_audio_quality": None,
    "redact_pii_audio_options": None,
    "redact_pii_policies": None,
    "redact_pii_sub": None,
    "speaker_labels": True,
    "speaker_options": None,
    "content_safety": False,
    "iab_categories": False,
    "content_safety_labels": {"status": "unavailable", "results": [], "summary": {}},
    "iab_categories_result": {"status": "unavailable", "results": [], "summary": {}},
    "language_detection": False,
    "language_confidence_threshold": None,
    "language_confidence": None,
    "custom_spelling": None,
    "throttled": False,
    "auto_chapters": False,
    "summarization": False,
    "summary_type": None,
    "summary_model": None,
    "custom_topics": False,
    "topics": [],
    "speech_threshold": None,
    "speech_model": None,
    "chapters": None,
    "disfluencies": False,
    "entity_detection": False,
    "sentiment_analysis": False,
    "sentiment_analysis_results": None,
    "entities": None,
    "speakers_expected": None,
    "summary": None,
    "custom_topics_results": None,
    "is_deleted": None,
    "multichannel": None,
    "project_id": 643006,
    "token_id": 647999,
}


def test_create_discussion_from_transcript_success(flask_app, auditor):
    response = auditor.post(
        f"/therapist/discussions/transcript?diagram_id={auditor.user.free_diagram_id}",
        json=ASSEMBLY_AI_TRANSCRIPT_JSON,
    )

    assert response.status_code == 200
    data = response.get_json()
    assert "discussion_id" in data
    assert isinstance(data["discussion_id"], int) or isinstance(
        data["discussion_id"], str
    )
    discussion = Discussion.query.get(data["discussion_id"])
    assert len(discussion.statements) == len(ASSEMBLY_AI_TRANSCRIPT_JSON["utterances"])
    speakers = set(u["speaker"] for u in ASSEMBLY_AI_TRANSCRIPT_JSON["utterances"])
    assert len(speakers) == len(discussion.speakers) == 2
