"""The app's database, from empty: every table the models declare, in one
revision (R-0417). It replaces the chain 1a00000000aa..1a00000000af; a database
already at 1a00000000af is stamped to this revision once, never upgraded.

Revision ID: 1b00000000aa
Revises:
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1b00000000aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('admin_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('scope_id', sa.Integer(), nullable=True),
    sa.Column('value', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'scope_id', name='uq_admin_settings_key_scope')
    )
    with op.batch_alter_table('admin_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_settings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_settings_key'), ['key'], unique=False)

    op.create_table('discussions',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('diagram_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('title_set_by_user', sa.Boolean(), nullable=False, comment='Whether the title was given by hand rather than written by the coach'),
    sa.Column('kind', sa.Enum('chat', 'recording', 'note', name='discussionkind'), server_default='chat', nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('discussion_date', sa.Date(), nullable=True, comment='Date of the actual discussion/session (for accurate relative date extraction)'),
    sa.Column('last_topic', sa.Text(), nullable=True, comment='A the topic that the model should follow the user on, e.g. presenting problem, new issue'),
    sa.Column('status', sa.Enum('pending', 'generating', 'failed', 'pending_extraction', 'extracting', 'ready', name='discussionstatus'), server_default='pending', nullable=False),
    sa.Column('extracting', sa.Boolean(), nullable=False, comment="Whether background extraction job should run for this discussion's statements"),
    sa.Column('synthetic', sa.Boolean(), nullable=False, comment='Whether this discussion was generated by synthetic conversation testing'),
    sa.Column('synthetic_persona', sa.JSON(), nullable=True, comment='Persona data for synthetic conversations (name, background, traits, presenting_problem)'),
    sa.Column('synthetic_persona_id', sa.Integer(), nullable=True, comment='FK to synthetic_personas for generated persona linkage'),
    sa.Column('calibration_report', sa.JSON(), nullable=True),
    sa.Column('calibration_advice', sa.JSON(), nullable=True),
    sa.Column('statement_reviews', sa.JSON(), nullable=True),
    sa.Column('extracted_through_order', sa.Integer(), nullable=True, comment='Re-extraction cursor: highest Statement.order whose extraction has been accepted/committed. NULL = nothing accepted yet (extract from the start, legacy behaviour). Advances only on full PDP accept.'),
    sa.Column('pending_extracted_through_order', sa.Integer(), nullable=True, comment='Max Statement.order included in the most recent extract, held until that PDP is accepted; on full accept it is promoted to extracted_through_order. NULL when no extract awaits acceptance.'),
    sa.Column('chat_user_speaker_id', sa.Integer(), nullable=True, comment='The user speaker in a chat context'),
    sa.Column('chat_ai_speaker_id', sa.Integer(), nullable=True, comment='The AI speaker in a chat context'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['diagram_id'], ['diagrams.id'], ),
    sa.ForeignKeyConstraint(['synthetic_persona_id'], ['synthetic_personas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discussions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discussions_id'), ['id'], unique=False)

    op.create_table('invitations',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invitations_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitations_token'), ['token'], unique=True)

    op.create_table('login_codes',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('tries', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_codes_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_codes_id'), ['id'], unique=False)

    op.create_table('policies',
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('interval', sa.String(length=32), nullable=True),
    sa.Column('product', sa.String(length=128), nullable=True),
    sa.Column('maxActivations', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('amount', sa.Float(precision=2), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policies_id'), ['id'], unique=False)

    op.create_table('review_rules',
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('drafted_by', sa.Enum('ai', 'migration', 'human', name='rulesource'), nullable=False),
    sa.Column('flags', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('ratified_at', sa.DateTime(), nullable=True),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_rules_id'), ['id'], unique=False)

    op.create_table('speakers',
    sa.Column('discussion_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('type', sa.Enum('Expert', 'Subject', name='speakertype'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['discussion_id'], ['discussions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('speakers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_speakers_id'), ['id'], unique=False)

    op.create_table('synthetic_personas',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('background', sa.Text(), nullable=False),
    sa.Column('traits', sa.JSON(), nullable=False),
    sa.Column('attachment_style', sa.Text(), nullable=False),
    sa.Column('presenting_problem', sa.Text(), nullable=False),
    sa.Column('data_points', sa.JSON(), nullable=True),
    sa.Column('sex', sa.Text(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('synthetic_personas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_synthetic_personas_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), server_default='', nullable=False),
    sa.Column('reset_password_code', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('secret', sa.String(length=64), nullable=True),
    sa.Column('roles', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=100), server_default='', nullable=False),
    sa.Column('last_name', sa.String(length=100), server_default='', nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('preferences', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('stripe_id', sa.String(length=200), nullable=True),
    sa.Column('free_diagram_id', sa.Integer(), nullable=True),
    sa.Column('current_diagram_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['current_diagram_id'], ['diagrams.id'], use_alter=True),
    sa.ForeignKeyConstraint(['free_diagram_id'], ['diagrams.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('diagrams',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('alias', sa.String(), nullable=True),
    sa.Column('use_real_names', sa.Boolean(), nullable=True),
    sa.Column('require_password_for_real_names', sa.Boolean(), nullable=True),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diagrams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diagrams_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagrams_user_id'), ['user_id'], unique=False)

    op.create_table('licenses',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('canceled', sa.Boolean(), nullable=True),
    sa.Column('stripe_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    with op.batch_alter_table('licenses', schema=None) as batch_op:
        batch_op.create_index('(no name)', ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_licenses_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_licenses_user_id'), ['user_id'], unique=False)

    op.create_table('passkeys',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.String(length=255), nullable=False),
    sa.Column('public_key', sa.LargeBinary(), nullable=False),
    sa.Column('sign_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('transports', sa.JSON(), nullable=False),
    sa.Column('name', sa.String(length=255), server_default='', nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('passkeys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_passkeys_credential_id'), ['credential_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_passkeys_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_passkeys_user_id'), ['user_id'], unique=False)

    op.create_table('statements',
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('discussion_id', sa.Integer(), nullable=True),
    sa.Column('speaker_id', sa.Integer(), nullable=True),
    sa.Column('pdp_deltas', sa.JSON(), nullable=True),
    sa.Column('views', sa.JSON(), nullable=True),
    sa.Column('kind', sa.Enum('turn', 'play', name='statementkind'), nullable=False),
    sa.Column('cluster_id', sa.String(length=64), nullable=True),
    sa.Column('custom_prompts', sa.JSON(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('exported_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['discussion_id'], ['discussions.id'], ),
    sa.ForeignKeyConstraint(['speaker_id'], ['speakers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('statements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_statements_id'), ['id'], unique=False)

    op.create_table('token_meters',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_creation_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('cap', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'period', name='one_meter_a_month')
    )
    with op.batch_alter_table('token_meters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_meters_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_token_meters_user_id'), ['user_id'], unique=False)

    op.create_table('web_sessions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('user_agent', sa.String(length=255), server_default='', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('web_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_web_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_web_sessions_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_web_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('access_rights',
    sa.Column('diagram_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('right', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['diagram_id'], ['diagrams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('access_rights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_rights_diagram_id'), ['diagram_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_rights_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_rights_user_id'), ['user_id'], unique=False)

    op.create_table('diagram_changes',
    sa.Column('diagram_id', sa.Integer(), nullable=False),
    sa.Column('statement_id', sa.Integer(), nullable=True),
    sa.Column('turn_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('author', sa.Enum('user', 'coach', 'pro', 'review', name='author'), nullable=False),
    sa.Column('deltas', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['diagram_id'], ['diagrams.id'], ),
    sa.ForeignKeyConstraint(['statement_id'], ['statements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diagram_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diagram_changes_diagram_id'), ['diagram_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagram_changes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagram_changes_turn_id'), ['turn_id'], unique=False)

    op.create_table('diagram_interactions',
    sa.Column('diagram_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('statement_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Enum('look', 'say', 'chip_tap', 'play', name='interactionkind'), nullable=False),
    sa.Column('item_kind', sa.Enum('person', 'event', 'pair_bond', 'emotion', 'cluster', 'diagram', name='itemkind'), nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['diagram_id'], ['diagrams.id'], ),
    sa.ForeignKeyConstraint(['statement_id'], ['statements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diagram_interactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diagram_interactions_diagram_id'), ['diagram_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagram_interactions_id'), ['id'], unique=False)

    op.create_table('model_calls',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('diagram_id', sa.Integer(), nullable=False),
    sa.Column('turn_id', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('fallback', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_creation_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('tool_calls', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['diagram_id'], ['diagrams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_calls_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_calls_turn_id'), ['turn_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_calls_user_id'), ['user_id'], unique=False)

    op.create_table('product_events',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('diagram_id', sa.Integer(), nullable=True),
    sa.Column('screen', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('item_kind', sa.String(length=32), nullable=True),
    sa.Column('item_id', sa.String(length=64), nullable=True),
    sa.Column('client_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['diagram_id'], ['diagrams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_events_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_product_events_user_id_created_at', ['user_id', 'created_at'], unique=False)

    op.create_table('review_cuts',
    sa.Column('discussion_id', sa.Integer(), nullable=False),
    sa.Column('start_statement_id', sa.Integer(), nullable=False),
    sa.Column('end_statement_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('meeting_date', sa.Date(), nullable=True),
    sa.Column('vote_opened_at', sa.DateTime(), nullable=True),
    sa.Column('nudged_at', sa.DateTime(), nullable=True),
    sa.Column('ratified_at', sa.DateTime(), nullable=True),
    sa.Column('agreement', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('audit', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['discussion_id'], ['discussions.id'], ),
    sa.ForeignKeyConstraint(['end_statement_id'], ['statements.id'], ),
    sa.ForeignKeyConstraint(['start_statement_id'], ['statements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_cuts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_cuts_discussion_id'), ['discussion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_cuts_id'), ['id'], unique=False)

    op.create_table('review_codings',
    sa.Column('cut_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('diagram_id', sa.Integer(), nullable=False),
    sa.Column('agent', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('done_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cut_id'], ['review_cuts.id'], ),
    sa.ForeignKeyConstraint(['diagram_id'], ['diagrams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cut_id', 'user_id', name='uq_review_codings_cut_user')
    )
    with op.batch_alter_table('review_codings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_codings_cut_id'), ['cut_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_codings_id'), ['id'], unique=False)

    op.create_table('review_items',
    sa.Column('cut_id', sa.Integer(), nullable=False),
    sa.Column('item_kind', sa.Enum('person', 'event', 'pair_bond', 'emotion', 'cluster', 'diagram', name='itemkind'), nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=True),
    sa.Column('opinions', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('status', sa.Enum('agreed', 'disputed', 'decided', 'unresolved', name='reviewstatus'), nullable=False),
    sa.Column('ambiguous', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('decision_change_id', sa.Integer(), nullable=True),
    sa.Column('kept_coding_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cut_id'], ['review_cuts.id'], ),
    sa.ForeignKeyConstraint(['decision_change_id'], ['diagram_changes.id'], ),
    sa.ForeignKeyConstraint(['kept_coding_id'], ['review_codings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_items_cut_id'), ['cut_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_items_id'), ['id'], unique=False)

    op.create_table('review_notes',
    sa.Column('coding_id', sa.Integer(), nullable=False),
    sa.Column('statement_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('turn_id', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['coding_id'], ['review_codings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_notes_coding_id'), ['coding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_notes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_notes_statement_id'), ['statement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_notes_turn_id'), ['turn_id'], unique=False)

    op.create_table('review_votes',
    sa.Column('review_item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('choice', sa.Enum('opinion', 'change', 'drop', name='votechoice'), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['review_item_id'], ['review_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_item_id', 'user_id', name='uq_review_votes_item_user')
    )
    with op.batch_alter_table('review_votes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_votes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_votes_review_item_id'), ['review_item_id'], unique=False)
    # the tables that point at each other get those links once both exist
    with op.batch_alter_table('discussions', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_discussions_chat_ai_speaker_id_speakers', 'speakers', ['chat_ai_speaker_id'], ['id'])
    with op.batch_alter_table('discussions', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_discussions_chat_user_speaker_id_speakers', 'speakers', ['chat_user_speaker_id'], ['id'])
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_users_current_diagram_id_diagrams', 'diagrams', ['current_diagram_id'], ['id'])
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_users_free_diagram_id_diagrams', 'diagrams', ['free_diagram_id'], ['id'])


def downgrade():
    with op.batch_alter_table('discussions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_discussions_chat_ai_speaker_id_speakers', type_='foreignkey')
    with op.batch_alter_table('discussions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_discussions_chat_user_speaker_id_speakers', type_='foreignkey')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_current_diagram_id_diagrams', type_='foreignkey')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_free_diagram_id_diagrams', type_='foreignkey')
    with op.batch_alter_table('review_votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_votes_review_item_id'))
        batch_op.drop_index(batch_op.f('ix_review_votes_id'))

    op.drop_table('review_votes')
    with op.batch_alter_table('review_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_notes_turn_id'))
        batch_op.drop_index(batch_op.f('ix_review_notes_statement_id'))
        batch_op.drop_index(batch_op.f('ix_review_notes_id'))
        batch_op.drop_index(batch_op.f('ix_review_notes_coding_id'))

    op.drop_table('review_notes')
    with op.batch_alter_table('review_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_items_id'))
        batch_op.drop_index(batch_op.f('ix_review_items_cut_id'))

    op.drop_table('review_items')
    with op.batch_alter_table('review_codings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_codings_id'))
        batch_op.drop_index(batch_op.f('ix_review_codings_cut_id'))

    op.drop_table('review_codings')
    with op.batch_alter_table('review_cuts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_cuts_id'))
        batch_op.drop_index(batch_op.f('ix_review_cuts_discussion_id'))

    op.drop_table('review_cuts')
    with op.batch_alter_table('product_events', schema=None) as batch_op:
        batch_op.drop_index('ix_product_events_user_id_created_at')
        batch_op.drop_index(batch_op.f('ix_product_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_product_events_id'))

    op.drop_table('product_events')
    with op.batch_alter_table('model_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_calls_user_id'))
        batch_op.drop_index(batch_op.f('ix_model_calls_turn_id'))
        batch_op.drop_index(batch_op.f('ix_model_calls_id'))

    op.drop_table('model_calls')
    with op.batch_alter_table('diagram_interactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diagram_interactions_id'))
        batch_op.drop_index(batch_op.f('ix_diagram_interactions_diagram_id'))

    op.drop_table('diagram_interactions')
    with op.batch_alter_table('diagram_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diagram_changes_turn_id'))
        batch_op.drop_index(batch_op.f('ix_diagram_changes_id'))
        batch_op.drop_index(batch_op.f('ix_diagram_changes_diagram_id'))

    op.drop_table('diagram_changes')
    with op.batch_alter_table('access_rights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_rights_user_id'))
        batch_op.drop_index(batch_op.f('ix_access_rights_id'))
        batch_op.drop_index(batch_op.f('ix_access_rights_diagram_id'))

    op.drop_table('access_rights')
    with op.batch_alter_table('web_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_web_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_web_sessions_token'))
        batch_op.drop_index(batch_op.f('ix_web_sessions_id'))

    op.drop_table('web_sessions')
    with op.batch_alter_table('token_meters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_meters_user_id'))
        batch_op.drop_index(batch_op.f('ix_token_meters_id'))

    op.drop_table('token_meters')
    with op.batch_alter_table('statements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_statements_id'))

    op.drop_table('statements')
    with op.batch_alter_table('passkeys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_passkeys_user_id'))
        batch_op.drop_index(batch_op.f('ix_passkeys_id'))
        batch_op.drop_index(batch_op.f('ix_passkeys_credential_id'))

    op.drop_table('passkeys')
    with op.batch_alter_table('licenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_licenses_user_id'))
        batch_op.drop_index(batch_op.f('ix_licenses_id'))
        batch_op.drop_index('(no name)')

    op.drop_table('licenses')
    with op.batch_alter_table('diagrams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diagrams_user_id'))
        batch_op.drop_index(batch_op.f('ix_diagrams_id'))

    op.drop_table('diagrams')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('synthetic_personas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_synthetic_personas_id'))

    op.drop_table('synthetic_personas')
    with op.batch_alter_table('speakers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_speakers_id'))

    op.drop_table('speakers')
    with op.batch_alter_table('review_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_rules_id'))

    op.drop_table('review_rules')
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policies_id'))

    op.drop_table('policies')
    with op.batch_alter_table('login_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_codes_id'))
        batch_op.drop_index(batch_op.f('ix_login_codes_email'))

    op.drop_table('login_codes')
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invitations_token'))
        batch_op.drop_index(batch_op.f('ix_invitations_id'))
        batch_op.drop_index(batch_op.f('ix_invitations_email'))

    op.drop_table('invitations')
    with op.batch_alter_table('discussions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discussions_id'))

    op.drop_table('discussions')
    with op.batch_alter_table('admin_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_settings_key'))
        batch_op.drop_index(batch_op.f('ix_admin_settings_id'))

    op.drop_table('admin_settings')
