"""
Validate cumulative F1 on T7-5 fresh GT discussions.

Runs calculate_cumulative_f1() on discussions 50, 51, 52 (T7-5 synthetic
discussions with GT coded by Patrick in T7-6) and reports whether they
meet the target metrics:
  - People F1 > 0.7
  - Events F1 > 0.3

Usage:
    uv run python -m btcopilot.training.validate_t7_f1
    uv run python -m btcopilot.training.validate_t7_f1 --ids 50 51 52
    uv run python -m btcopilot.training.validate_t7_f1 --all-synthetic
    uv run python -m btcopilot.training.validate_t7_f1 --detailed
"""

import argparse
import sys

from btcopilot.app import create_app
from btcopilot.training.f1_metrics import (
    calculate_cumulative_f1,
    calculate_all_cumulative_f1,
    CumulativeF1Metrics,
)

# T7-5 fresh synthetic discussion IDs (generated by ConversationSimulator)
T7_5_DISCUSSION_IDS = [50, 51, 52]

# Target metrics from GitHub issue #27
TARGET_PEOPLE_F1 = 0.7
TARGET_EVENTS_F1 = 0.3


def validate_discussions(
    discussion_ids: list[int], detailed: bool = False
) -> list[CumulativeF1Metrics]:
    """Run cumulative F1 on specified discussions and return metrics."""
    from btcopilot.personal.models import Discussion

    results = []
    errors = []

    for disc_id in discussion_ids:
        discussion = Discussion.query.get(disc_id)
        if not discussion:
            errors.append((disc_id, "Discussion not found"))
            continue

        try:
            metrics = calculate_cumulative_f1(disc_id)
            results.append(metrics)
        except ValueError as e:
            errors.append((disc_id, str(e)))

    if errors:
        print("ERRORS:")
        for disc_id, err in errors:
            print(f"  Discussion {disc_id}: {err}")
        print()

    return results


def print_report(results: list[CumulativeF1Metrics], detailed: bool = False):
    """Print formatted F1 report with pass/fail against targets."""
    if not results:
        print("No results to report.")
        return

    # Header
    print("=" * 72)
    print("T7-7: Cumulative F1 Validation Report")
    print(f"Targets: People F1 > {TARGET_PEOPLE_F1}, Events F1 > {TARGET_EVENTS_F1}")
    print("=" * 72)
    print()

    # Per-discussion results
    all_pass = True
    for m in results:
        people_pass = m.people_f1 > TARGET_PEOPLE_F1
        events_pass = m.events_f1 > TARGET_EVENTS_F1
        disc_pass = people_pass and events_pass

        status = "PASS" if disc_pass else "FAIL"
        if not disc_pass:
            all_pass = False

        print(f"Discussion {m.discussion_id}: {m.discussion_summary}")
        print(f"  Auditor: {m.auditor_id}")
        print(f"  People F1:     {m.people_f1:.3f}  {'PASS' if people_pass else 'FAIL'}  (target > {TARGET_PEOPLE_F1})")
        print(f"    TP={m.people_metrics.tp}, FP={m.people_metrics.fp}, FN={m.people_metrics.fn}")
        print(f"    AI extracted: {m.ai_people_count}, GT expected: {m.gt_people_count}")
        print(f"  Events F1:     {m.events_f1:.3f}  {'PASS' if events_pass else 'FAIL'}  (target > {TARGET_EVENTS_F1})")
        print(f"    TP={m.events_metrics.tp}, FP={m.events_metrics.fp}, FN={m.events_metrics.fn}")
        print(f"    AI extracted: {m.ai_events_count}, GT expected: {m.gt_events_count}")
        print(f"  PairBonds F1:  {m.pair_bonds_f1:.3f}")
        print(f"    TP={m.pair_bonds_metrics.tp}, FP={m.pair_bonds_metrics.fp}, FN={m.pair_bonds_metrics.fn}")
        print(f"  Aggregate F1:  {m.aggregate_micro_f1:.3f}")
        print(f"  Status: [{status}]")

        if detailed and m.events_metrics.tp > 0:
            print(f"  SARF macro F1: symptom={m.symptom_macro_f1:.3f}, "
                  f"anxiety={m.anxiety_macro_f1:.3f}, "
                  f"relationship={m.relationship_macro_f1:.3f}, "
                  f"functioning={m.functioning_macro_f1:.3f}")

        print()

    # Aggregate
    n = len(results)
    avg_people = sum(r.people_f1 for r in results) / n
    avg_events = sum(r.events_f1 for r in results) / n
    avg_bonds = sum(r.pair_bonds_f1 for r in results) / n
    avg_agg = sum(r.aggregate_micro_f1 for r in results) / n

    print("-" * 72)
    print(f"AGGREGATE ({n} discussions)")
    print(f"  Avg People F1:     {avg_people:.3f}  {'PASS' if avg_people > TARGET_PEOPLE_F1 else 'FAIL'}")
    print(f"  Avg Events F1:     {avg_events:.3f}  {'PASS' if avg_events > TARGET_EVENTS_F1 else 'FAIL'}")
    print(f"  Avg PairBonds F1:  {avg_bonds:.3f}")
    print(f"  Avg Aggregate F1:  {avg_agg:.3f}")
    print()

    # Failure analysis
    failures = []
    for m in results:
        if m.people_f1 <= TARGET_PEOPLE_F1:
            failures.append(
                f"  Discussion {m.discussion_id}: People F1={m.people_f1:.3f} "
                f"(FP={m.people_metrics.fp} extra, FN={m.people_metrics.fn} missed)"
            )
        if m.events_f1 <= TARGET_EVENTS_F1:
            failures.append(
                f"  Discussion {m.discussion_id}: Events F1={m.events_f1:.3f} "
                f"(FP={m.events_metrics.fp} extra, FN={m.events_metrics.fn} missed)"
            )

    if failures:
        print("FAILURE PATTERNS:")
        for f in failures:
            print(f)
        print()

    # Zero pair bonds check (known issue from F1_METRICS.md)
    zero_bonds = [m for m in results if m.pair_bonds_f1 == 0.0 and m.pair_bonds_metrics.fn > 0]
    if zero_bonds:
        print("NOTE: AI extracts zero pair bonds (known gap, see F1_METRICS.md):")
        for m in zero_bonds:
            print(f"  Discussion {m.discussion_id}: GT has {m.pair_bonds_metrics.fn} pair bonds, AI has 0")
        print()

    # Final verdict
    print("=" * 72)
    if all_pass:
        print("RESULT: ALL DISCUSSIONS PASS TARGET METRICS")
    else:
        passing = sum(1 for m in results if m.people_f1 > TARGET_PEOPLE_F1 and m.events_f1 > TARGET_EVENTS_F1)
        print(f"RESULT: {passing}/{n} DISCUSSIONS PASS TARGET METRICS")
    print("=" * 72)

    return all_pass


def main():
    parser = argparse.ArgumentParser(
        description="Validate cumulative F1 on T7-5 discussions"
    )
    parser.add_argument(
        "--ids",
        nargs="+",
        type=int,
        default=None,
        help=f"Discussion IDs to validate (default: {T7_5_DISCUSSION_IDS})",
    )
    parser.add_argument(
        "--all-synthetic",
        action="store_true",
        help="Run on all synthetic discussions with approved GT",
    )
    parser.add_argument(
        "--detailed",
        action="store_true",
        help="Show SARF macro F1 breakdown",
    )
    args = parser.parse_args()

    app = create_app()
    with app.app_context():
        if args.all_synthetic:
            print("Running cumulative F1 on all synthetic discussions with GT...\n")
            system = calculate_all_cumulative_f1(include_synthetic=True)
            if not system.per_discussion:
                print("No discussions with approved GT found. Please ensure that the discussions exist and have approved ground truth.")
                sys.exit(1)
            print_report(system.per_discussion, detailed=args.detailed)
        else:
            ids = args.ids or T7_5_DISCUSSION_IDS
            print(f"Running cumulative F1 on discussions: {ids}\n")
            results = validate_discussions(ids, detailed=args.detailed)
            if not results:
                print("No valid results. Check that discussions exist and have approved GT. Please ensure that the discussion IDs are correct and that approved ground truth data is available.")
                sys.exit(1)
            all_pass = print_report(results, detailed=args.detailed)
            sys.exit(0 if all_pass else 1)


if __name__ == "__main__":
    main()
